name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: List files in app directory
        run: ls -la app

      - name: Make gradlew executable
        run: chmod +x app/gradlew  # Или используйте $GITHUB_WORKSPACE/app/gradlew

      - name: Run lint
        run: make -C app lint
